# export keys in your .profile file
development: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || '4ae66f25c3481019eefdb4d18c035b680195660540bda35b3e0a2003c20a74d36dcf96a959da1ea8e5dfc3f5613d277556df462c8558bfab58047e8c683306c3' %>
  # sending emails
  mandrill_api_key: <%= ENV['MANDRILL_API_KEY'] %>
  mail_interceptor_email: <%= ENV['MAIL_INTERCEPTOR_EMAIL'] %>

test: *default
production: *default

